[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "light"
primaryColor = "#52181E"
backgroundColor = "#F8F8F8"
secondaryBackgroundColor = "#e2999b"
textColor = "#000000"
font = "sans-serif"
